//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Objects.DataClasses;

namespace _01_InventoryEDMConsoleApp
{
  using System;
  using System.Collections.Generic;

  public partial class Car
  {
    public int CarId { get; set; }
    public string Make { get; set; }
    public string Color { get; set; }
    public string CarNickName { get; set; }
  }
}
